a = int(input("Ingresa el valor de a"))
b = int(input("Ingresa el valor de b"))
sum = (a + b)
rest = (a - b)
div = (a / b)
mult = (a * b)
print ("El resultado de las operaciones son: Suma ", sum, " Resta ", rest, " División ", div, " Multiplicación ", mult)
